name: Build Xeris Smart Contract

on:
  push:
    paths:
      - 'smart-contract/**'
  workflow_dispatch: # Allows you to manually trigger the build

jobs:
  build-anchor-program:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./smart-contract

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true

      - name: Install Solana CLI
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/v1.17.16/install)"
          echo "/home/runner/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      - name: Install Anchor CLI
        run: |
          cargo install --git https://github.com/coral-xyz/anchor avm --locked --force
          avm install 0.29.0
          avm use 0.29.0

      - name: Build Contract
        run: anchor build

      - name: Upload Compiled Contract
        uses: actions/upload-artifact@v3
        with:
          name: xeris-crash-executable
          path: smart-contract/target/deploy/xeris_crash.so
